ktor:
  application:
    modules:
      - gg.growly.cloudconstruct.worker.ApplicationKt.module
  deployment:
    port: 5353

# Gemini configuration
gemini:
  apiKey: "" # set your API key here or via env-specific yaml
  model: "gemini-2.5-flash"

# Database configuration
db:
  mongo:
    host: 127.0.0.1
    port: 27017
    database:
      name: cloudconstruct-live
